# Generated by Django 3.0 on 2021-11-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_auto_20211129_2236'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjects',
            fields=[
                ('teacher_subjectcode', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_subjectsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
                ('teacher_subjectteacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teachers')),
            ],
        ),
    ]
