# Generated by Django 3.0 on 2021-12-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachersubjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjects',
            name='teacher_subjectclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses'),
        ),
    ]
