# Generated by Django 3.0 on 2022-01-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0010_students_year_of_completion'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveouts',
            fields=[
                ('leave_code', models.AutoField(primary_key=True, serialize=False)),
                ('leave_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('date_expected_back', models.DateTimeField(blank=True, null=True)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('leave_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('leave_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
                ('user_leaveauthoriser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_authorised_foreignkey', to=settings.AUTH_USER_MODEL)),
                ('user_returnauthoriser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_return_foreignkey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
