# Generated by Django 3.0 on 2022-01-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveouts',
            name='leave_returned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
