# Generated by Django 3.0 on 2021-12-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('termdates', '0001_initial'),
        ('gradingsystem', '0001_initial'),
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('exam_reg_code', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=200)),
                ('mother_address', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('effective_date', models.DateTimeField()),
                ('final_exam', models.BooleanField(default=False)),
                ('combined_exam', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField()),
                ('exam_grading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradingsystem.GradingSystem')),
                ('exam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
                ('exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years')),
            ],
        ),
    ]
