# Generated by Django 3.0 on 2021-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_examregistration_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
