# Generated by Django 3.0 on 2021-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_examregistration_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
    ]
