# Generated by Django 3.0 on 2021-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_examregistration_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='exam_national',
            field=models.BooleanField(default=False),
        ),
    ]
