# Generated by Django 3.0 on 2021-12-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('registration', '0005_examregistration_exam_national'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='exam_grading',
        ),
        migrations.AddField(
            model_name='examregistration',
            name='exam_grade_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.GradingSchemes'),
        ),
    ]
