# Generated by Django 3.0 on 2021-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20211209_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='mother_address',
        ),
    ]
