# Generated by Django 3.0 on 2022-01-21 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountmaster', '0002_accountmaster_account_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatReplenishment',
            fields=[
                ('float_code', models.AutoField(primary_key=True, serialize=False)),
                ('float_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('float_docno', models.CharField(blank=True, max_length=200, null=True)),
                ('float_date', models.DateTimeField()),
                ('float_runningbalance', models.DecimalField(decimal_places=2, max_digits=13)),
                ('float_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountmaster.AccountMaster')),
                ('float_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_assignee_foreignkey', to=settings.AUTH_USER_MODEL)),
                ('float_assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_assigner_foreignkey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
