# Generated by Django 3.0 on 2022-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatreplenishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatreplenishment',
            name='float_accbal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='floatreplenishment',
            name='float_prevbal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='floatreplenishment',
            name='float_runningbalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
