# Generated by Django 3.0 on 2022-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatreplenishment', '0002_auto_20220121_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatreplenishment',
            name='float_payeebal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
