# Generated by Django 3.0 on 2022-01-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('accountsub_code', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('account_serial', models.CharField(max_length=200)),
                ('account_order', models.IntegerField(default=0)),
                ('account_main', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=400)),
                ('account_status', models.BooleanField(default=True)),
                ('account_drcr', models.CharField(blank=True, max_length=200, null=True)),
                ('account_reconcile', models.CharField(blank=True, max_length=200, null=True)),
                ('account_restrictpost', models.CharField(blank=True, max_length=200, null=True)),
                ('account_cashbook', models.CharField(blank=True, max_length=200, null=True)),
                ('account_trialbalance', models.CharField(blank=True, max_length=200, null=True)),
                ('account_tradingaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('account_balancesheet', models.CharField(blank=True, max_length=200, null=True)),
                ('account_incomeexpenditure', models.CharField(blank=True, max_length=200, null=True)),
                ('account_profitloss', models.CharField(blank=True, max_length=200, null=True)),
                ('account_pettycash', models.CharField(blank=True, max_length=200, null=True)),
                ('account_accountgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountgroups.AccountGroups')),
                ('account_mainaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountmaster.AccountMaster')),
            ],
        ),
    ]
