# Generated by Django 3.0 on 2022-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmaster',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
