# Generated by Django 3.0 on 2021-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorms',
            fields=[
                ('dorm_code', models.AutoField(primary_key=True, serialize=False)),
                ('dorm_name', models.CharField(max_length=200)),
                ('max_capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
