# Generated by Django 3.0 on 2021-11-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorms',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
