# Generated by Django 3.0 on 2022-01-04 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankbranches', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termdates', '0001_initial'),
        ('paymentmodes', '0001_initial'),
        ('student', '0010_students_year_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('payment_code', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_docno', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('payment_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankbranches.BankBranches')),
                ('payment_capturedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentmodes.PaymentModes')),
                ('payment_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
            ],
        ),
    ]
