# Generated by Django 3.0 on 2022-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recievefees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_receiptno',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
