# Generated by Django 3.0 on 2021-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSchemes',
            fields=[
                ('scheme_code', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=200)),
            ],
        ),
    ]
