# Generated by Django 3.0 on 2021-12-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20211209_2110'),
        ('gradingsystem', '0004_auto_20211209_2110'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradingSchemes',
        ),
    ]
