# Generated by Django 3.0 on 2021-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='mandatory_subject',
            field=models.BooleanField(default=False),
        ),
    ]
