# Generated by Django 3.2.7 on 2021-10-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Select2Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=200)),
                ('county_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=200)),
                ('country_continent', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDef',
            fields=[
                ('stdCode', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('town', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('stud_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.countries')),
                ('stud_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.counties')),
            ],
        ),
        migrations.AddField(
            model_name='counties',
            name='county_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.countries'),
        ),
    ]
