# Generated by Django 3.0 on 2021-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdef',
            name='photo',
            field=models.ImageField(null=True, upload_to='parents'),
        ),
    ]
