# Generated by Django 3.0 on 2022-04-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('termdates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesTracker',
            fields=[
                ('doubletracker_code', models.AutoField(primary_key=True, serialize=False)),
                ('doubletracker_number', models.IntegerField(default=0)),
                ('doubletracker_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('doubletracker_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
                ('doubletracker_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
            ],
        ),
    ]
