# Generated by Django 3.0 on 2021-12-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feecategories', '0001_initial'),
        ('student', '0010_students_year_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTracker',
            fields=[
                ('tracker_code', models.AutoField(primary_key=True, serialize=False)),
                ('tracker_notes', models.CharField(max_length=600)),
                ('tracker_date', models.DateTimeField()),
                ('tracker_type', models.CharField(blank=True, max_length=200, null=True)),
                ('tracker_invoiceno', models.CharField(blank=True, max_length=200, null=True)),
                ('structure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories')),
                ('tracker_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
            ],
        ),
    ]
