# Generated by Django 3.0 on 2022-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleinvoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetracker',
            name='tracker_currentbalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
