# Generated by Django 3.0 on 2022-02-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleinvoicing', '0002_balancetracker_tracker_currentbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetracker',
            name='tracker_currentbalance',
        ),
    ]
