# Generated by Django 3.0 on 2021-10-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasses',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teachers'),
        ),
        migrations.AlterField(
            model_name='schoolclasses',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses'),
        ),
    ]
