# Generated by Django 3.0 on 2021-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('sequence_code', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
