# Generated by Django 3.0 on 2022-01-21 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashBalances',
            fields=[
                ('pettycashbalance_code', models.AutoField(primary_key=True, serialize=False)),
                ('pettycashbalance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('pettycashbalance_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
