# Generated by Django 3.0 on 2022-03-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('daysetups', '0001_initial'),
        ('timetabling', '0001_initial'),
        ('teachers', '0004_auto_20211129_2236'),
        ('termdates', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAllocation',
            fields=[
                ('timetable_code', models.AutoField(primary_key=True, serialize=False)),
                ('timetable_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('timetable_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daysetups.DaySetups')),
                ('timetable_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetabling.LessonSetups')),
                ('timetable_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
                ('timetable_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teachers')),
                ('timetable_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
            ],
        ),
    ]
