# Generated by Django 3.0 on 2022-03-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsetups', '0001_initial'),
        ('lessonallocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonallocation',
            name='timetable_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessonsetups.LessonSetups'),
        ),
    ]
