# Generated by Django 3.0 on 2022-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsetups', '0003_remove_lessonsetups_lesson_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsetups',
            name='lesson_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lessonsetups',
            name='lesson_start',
            field=models.DateTimeField(),
        ),
    ]
