# Generated by Django 3.0 on 2022-03-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsetups', '0004_auto_20220301_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsetups',
            name='lesson_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessonsetups',
            name='lesson_start',
            field=models.TimeField(),
        ),
    ]
