# Generated by Django 3.0 on 2021-11-23 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_code', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=200)),
                ('type_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date_created')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('user_teacher_ref', models.IntegerField(blank=True, default=0, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
