# Generated by Django 3.0 on 2021-11-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211104_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_teacher_ref',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
