# Generated by Django 3.0 on 2021-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('year_code', models.AutoField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=200)),
                ('year_number', models.IntegerField(default=0)),
            ],
        ),
    ]
