# Generated by Django 3.0 on 2021-12-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('gradingsystem', '0002_gradingsystem_default_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.GradingSchemes'),
        ),
    ]
