# Generated by Django 3.0 on 2022-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySetups',
            fields=[
                ('day_code', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=200)),
            ],
        ),
    ]
