# Generated by Django 3.0 on 2021-11-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('campus_code', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_incharge', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_inchargephone', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_location', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Counties')),
            ],
        ),
    ]
