# Generated by Django 3.0 on 2021-11-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuses',
            name='campus_incharge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campuses',
            name='campus_inchargephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campuses',
            name='campus_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campuses',
            name='campus_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
