# Generated by Django 3.0 on 2021-12-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSequences',
            fields=[
                ('sequence_code', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_type', models.CharField(max_length=200)),
                ('sequence_nextseq', models.BigIntegerField(default=0)),
                ('sequence_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Departments')),
            ],
        ),
    ]
