# Generated by Django 3.0 on 2022-03-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('classsubject_code', models.AutoField(primary_key=True, serialize=False)),
                ('lessons_perweek', models.IntegerField(default=0)),
                ('double_lessons', models.IntegerField(default=0)),
                ('stroked_subject', models.BooleanField(default=False)),
                ('stroked_with', models.IntegerField(default=0)),
                ('classsubject_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('classsubject_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
            ],
        ),
    ]
