# Generated by Django 3.0 on 2022-01-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0010_students_year_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketMoneyTracker',
            fields=[
                ('tracker_code', models.AutoField(primary_key=True, serialize=False)),
                ('tracker_date', models.DateTimeField()),
                ('tracker_invoiceno', models.CharField(blank=True, max_length=200, null=True)),
                ('tracker_balance', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('tracker_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
            ],
        ),
    ]
