# Generated by Django 3.0 on 2021-12-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('termdates', '0001_initial'),
        ('feecategories', '0001_initial'),
        ('years', '0001_initial'),
        ('standardcharges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('structure_code', models.AutoField(primary_key=True, serialize=False)),
                ('structure_ammount', models.BigIntegerField(default=0)),
                ('structure_Standardcharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standardcharges.StandardCharges')),
                ('structure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories')),
                ('structure_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
                ('structure_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years')),
            ],
        ),
    ]
