# Generated by Django 3.0 on 2022-01-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='adm_date',
        ),
    ]
