# Generated by Django 3.0 on 2021-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('denomination_code', models.AutoField(primary_key=True, serialize=False)),
                ('denomination_name', models.CharField(max_length=200)),
                ('denomination_day', models.CharField(max_length=200)),
            ],
        ),
    ]
