# Generated by Django 3.0 on 2021-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('denomination_code', models.AutoField(primary_key=True, serialize=False)),
                ('denomination_name', models.CharField(blank=True, max_length=200, null=True)),
                ('denomination_day', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
