# Generated by Django 3.0 on 2022-01-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pettycashsetups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PettyCashPayments',
        ),
    ]
