# Generated by Django 3.0 on 2022-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroups',
            fields=[
                ('accountgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('accountgroup_code', models.CharField(max_length=200)),
                ('accountgroup_serial', models.CharField(max_length=200)),
                ('accountgroup_name', models.CharField(max_length=400)),
            ],
        ),
    ]
