# Generated by Django 3.0 on 2021-12-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standardcharges', '0001_initial'),
        ('feestructure', '0002_auto_20211216_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructureDetails',
            fields=[
                ('structuredetail_code', models.AutoField(primary_key=True, serialize=False)),
                ('structuredetail_ammount', models.BigIntegerField(default=0)),
                ('structuredetail_Standardcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standardcharges.StandardCharges')),
                ('structuredetail_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feestructure.FeeStructure')),
            ],
        ),
    ]
