# Generated by Django 3.0 on 2022-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSetups',
            fields=[
                ('lesson_code', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_start', models.TimeField()),
                ('lesson_end', models.TimeField()),
                ('lesson_duration', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(blank=True, max_length=200, null=True)),
                ('lesson_auto', models.BooleanField(default=True)),
            ],
        ),
    ]
