# Generated by Django 3.0 on 2022-03-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonallocation', '0002_auto_20220301_1641'),
        ('timetabling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonSetups',
        ),
    ]
