# Generated by Django 3.0 on 2021-11-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_code', models.AutoField(primary_key=True, serialize=False)),
                ('subject_order', models.CharField(max_length=200)),
                ('subject_sht_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('main_subject', models.BooleanField(default=False)),
                ('combined_subject', models.BooleanField(default=False)),
                ('include_for_pos', models.BooleanField(default=False)),
                ('subject_multiplier', models.CharField(blank=True, max_length=200, null=True)),
                ('timetable_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mandatory_subject', models.BooleanField(default=False)),
                ('subject_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Departments')),
            ],
        ),
    ]
