# Generated by Django 3.0 on 2021-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211129_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
