# Generated by Django 3.0 on 2021-11-29 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0003_auto_20211129_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='finger_print_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_pic',
            field=models.ImageField(blank=True, null=True, upload_to='teacher-pics'),
        ),
    ]
