# Generated by Django 3.0 on 2022-01-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('glaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('bankbranch_code', models.AutoField(primary_key=True, serialize=False)),
                ('bankbranch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bankbranch_accountname', models.CharField(blank=True, max_length=200, null=True)),
                ('bankbranch_accountnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('bankbranch_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Banks')),
                ('bankbranch_glname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glaccounts.GlAccounts')),
            ],
        ),
    ]
