# Generated by Django 3.0 on 2021-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('type_code', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=200)),
                ('type_desc', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
