# Generated by Django 3.0 on 2021-12-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
        ('years', '0001_initial'),
        ('student', '0010_students_year_of_completion'),
        ('classes', '0001_initial'),
        ('teachers', '0004_auto_20211129_2236'),
        ('termdates', '0001_initial'),
        ('registration', '0008_remove_examregistration_mother_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProcessing',
            fields=[
                ('exam_process_code', models.AutoField(primary_key=True, serialize=False)),
                ('exam_marks', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_outof', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_processing_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_process_date', models.DateTimeField()),
                ('exam_percentage_marks', models.CharField(blank=True, max_length=200, null=True)),
                ('position_outof', models.CharField(blank=True, max_length=200, null=True)),
                ('position_persubject', models.CharField(blank=True, max_length=200, null=True)),
                ('position_perclass', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_marks', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_position', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_outof', models.CharField(blank=True, max_length=200, null=True)),
                ('stream_position', models.CharField(blank=True, max_length=200, null=True)),
                ('stream_positionoutof', models.CharField(blank=True, max_length=200, null=True)),
                ('class_mean_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('class_mean_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('form_mean_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('form_mean_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_process_remarks', models.CharField(blank=True, max_length=400, null=True)),
                ('exam_process_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('exam_process_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.ExamRegistration')),
                ('exam_process_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
                ('exam_process_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
                ('exam_process_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teachers')),
                ('exam_process_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
                ('exam_process_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years')),
                ('exam_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
