# Generated by Django 3.0 on 2021-12-15 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0002_marksexcelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_marks',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_outof',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_processed_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
