# Generated by Django 3.0 on 2021-12-15 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0003_auto_20211215_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_processed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_processing_grade',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
