# Generated by Django 3.0 on 2021-12-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20211215_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprocessing',
            name='exam_process_remarks',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
