# Generated by Django 3.0 on 2021-11-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('stud_doc_code', models.AutoField(primary_key=True, serialize=False)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='studentdocs')),
                ('stud_doc_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Documents')),
                ('stud_doc_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
            ],
        ),
    ]
