# Generated by Django 3.0 on 2021-12-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singleinvoicing', '0001_initial'),
        ('standardcharges', '0003_auto_20211217_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTrackerDetails',
            fields=[
                ('trackerdetails_code', models.AutoField(primary_key=True, serialize=False)),
                ('trackerdetails_balance', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('trackerdetails_Standardcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standardcharges.StandardCharges')),
                ('trackerdetails_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleinvoicing.BalanceTracker')),
            ],
        ),
    ]
