# Generated by Django 3.0 on 2021-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategories',
            fields=[
                ('category_code', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('category_desc', models.CharField(max_length=200)),
                ('default', models.BooleanField(default=True)),
                ('next_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories')),
            ],
        ),
    ]
