# Generated by Django 3.0 on 2021-10-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='parent_photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_pics'),
        ),
    ]
