# Generated by Django 3.0 on 2022-01-14 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0010_students_year_of_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketMoneyTrans',
            fields=[
                ('pocketmoney_code', models.AutoField(primary_key=True, serialize=False)),
                ('pocketmoney_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('pocketmoney_date', models.DateTimeField()),
                ('pocketmoney_transtype', models.CharField(max_length=200)),
                ('pocketmoney_addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pocketmoney_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
            ],
        ),
    ]
