# Generated by Django 3.0 on 2022-02-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocketmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketmoneytrans',
            name='pocketmoney_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
