# Generated by Django 3.0 on 2021-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCharges',
            fields=[
                ('charge_code', models.AutoField(primary_key=True, serialize=False)),
                ('charge_name', models.CharField(max_length=200)),
                ('charge_priority', models.IntegerField(default=0)),
                ('charge_acc_code', models.CharField(blank=True, max_length=200, null=True)),
                ('charge_refundable', models.BooleanField(default=False)),
                ('charge_type', models.CharField(blank=True, max_length=200, null=True)),
                ('charge_acc', models.CharField(blank=True, max_length=200, null=True)),
                ('charge_active', models.BooleanField(default=True)),
            ],
        ),
    ]
