# Generated by Django 3.0 on 2021-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardcharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcharges',
            name='charge_uiid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
