# Generated by Django 3.0 on 2021-12-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardcharges', '0002_standardcharges_charge_uiid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardcharges',
            name='charge_uiid',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
