# Generated by Django 3.0 on 2021-11-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feecategories', '0001_initial'),
        ('sources', '0001_initial'),
        ('years', '0001_initial'),
        ('studentstatus', '0001_initial'),
        ('localities', '0001_initial'),
        ('dorms', '0001_initial'),
        ('denominations', '0001_initial'),
        ('campuses', '0001_initial'),
        ('parents', '0001_initial'),
        ('healthconditions', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_code', models.AutoField(primary_key=True, serialize=False)),
                ('adm_no', models.CharField(blank=True, max_length=200, null=True)),
                ('student_upi', models.CharField(blank=True, max_length=200, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('adm_term', models.CharField(blank=True, max_length=200, null=True)),
                ('student_address', models.CharField(blank=True, max_length=200, null=True)),
                ('student_email', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('adm_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('birth_cert_no', models.CharField(blank=True, max_length=200, null=True)),
                ('index_no', models.CharField(blank=True, max_length=200, null=True)),
                ('marks', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_school', models.CharField(blank=True, max_length=200, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='studentphoto')),
                ('health_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthconditions.HealthStatus')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Countries')),
                ('stud_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Location')),
                ('stud_sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.SubCounty')),
                ('stud_sub_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.SubLocation')),
                ('stud_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Village')),
                ('student_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campuses.Campuses')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('student_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Counties')),
                ('student_denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denominations.Denomination')),
                ('student_dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorms.Dorms')),
                ('student_exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years')),
                ('student_fee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories')),
                ('student_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.Parents')),
                ('student_sources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.StudentSources')),
                ('student_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentstatus.StudentStatus')),
            ],
        ),
    ]
