# Generated by Django 3.0 on 2021-11-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0003_auto_20211112_0438'),
        ('feecategories', '0001_initial'),
        ('healthconditions', '0002_auto_20211114_1347'),
        ('denominations', '0002_auto_20211114_1347'),
        ('sources', '0002_auto_20211114_1347'),
        ('dorms', '0002_auto_20211114_1347'),
        ('campuses', '0002_auto_20211114_1347'),
        ('parents', '0003_auto_20211030_1258'),
        ('classes', '0003_auto_20211114_1347'),
        ('studentstatus', '0002_auto_20211114_1347'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='adm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='adm_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='adm_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_cert_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthconditions.HealthStatus'),
        ),
        migrations.AlterField(
            model_name='students',
            name='index_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='marks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Countries'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='primary_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Location'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.SubCounty'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.SubLocation'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Village'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campuses.Campuses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localities.Counties'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_denomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denominations.Denomination'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_dorm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorms.Dorms'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.Parents'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_sources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.StudentSources'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentstatus.StudentStatus'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_upi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
