# Generated by Django 3.0 on 2021-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211114_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='adm_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_upi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
