# Generated by Django 3.0 on 2021-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211123_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='stud_active_status',
        ),
    ]
