# Generated by Django 3.0 on 2021-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211114_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='adm_no',
        ),
        migrations.AddField(
            model_name='students',
            name='admission_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
