# Generated by Django 3.0 on 2021-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_students_stud_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_school_status',
            field=models.CharField(blank=True, default='Active', max_length=200, null=True),
        ),
    ]
