# Generated by Django 3.0 on 2021-11-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211114_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='admission_no',
            new_name='adm_no',
        ),
    ]
