# Generated by Django 3.0 on 2021-11-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0001_initial'),
        ('student', '0005_auto_20211114_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_exam_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years'),
        ),
    ]
