# Generated by Django 3.0 on 2021-11-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_students_student_school_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_school_status',
            field=models.CharField(blank=True, default='Active', max_length=200),
        ),
    ]
