# Generated by Django 3.0 on 2021-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211123_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_statuschange_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_statuschange_term',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
