# Generated by Django 3.0 on 2021-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_students_student_resume_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='year_of_completion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
