# Generated by Django 3.0 on 2022-01-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAudit',
            fields=[
                ('categoryaudit_code', models.AutoField(primary_key=True, serialize=False)),
                ('categoryaudit_dateassigned', models.DateTimeField()),
                ('categoryaudit_categoryfrom', models.CharField(max_length=200)),
                ('categoryaudit_categoryto', models.CharField(max_length=200)),
                ('categoryaudit_username', models.CharField(max_length=200)),
            ],
        ),
    ]
