# Generated by Django 3.0 on 2022-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlAccounts',
            fields=[
                ('glaccount_code', models.AutoField(primary_key=True, serialize=False)),
                ('glaccount_name', models.CharField(blank=True, max_length=200, null=True)),
                ('glaccount_desc', models.CharField(blank=True, max_length=400, null=True)),
                ('glaccount_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
